name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag nutrimax-search

    - name: Push the Docker image
      run: |
        docker tag nutrimax-search ${{ secrets.DOCKER_USERNAME }}/nutrimax-search:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/nutrimax-search:latest
